---
- name: Exist terraform
  ansible.builtin.command: which terraform
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_terraform
  changed_when: false
  ignore_errors: true

- name: Get terraform version
  ansible.builtin.shell: terraform version | grep Terraform
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_terraform
  changed_when: false
  ignore_errors: true
  when: exist_terraform.rc == 0

- block:
    - name: Get zip
      ansible.builtin.get_url:
        url: "{{ terraform.src }}"
        dest: /tmp/{{ terraform.zip }}

    - name: Unarchive zip
      ansible.builtin.unarchive:
        src: /tmp/{{ terraform.zip }}
        dest: /usr/local/bin/
        copy: false

  when: exist_terraform.rc != 0 or ( version_in_terraform is defined and version_in_terraform.stdout.find(terraform_version) == -1 )
