---
- name: Exist terraform
  ansible.builtin.command: which terraform
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: terraform_exist
  changed_when: false
  ignore_errors: true

- name: Get terraform version
  ansible.builtin.shell: terraform version | grep Terraform
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: terraform_current_version
  changed_when: false
  ignore_errors: true
  when: terraform_exist.rc == 0

- name: Check and install
  block:
    - name: Get zip
      ansible.builtin.get_url:
        url: "{{ terraform.src }}"
        dest: /tmp/{{ terraform.zip }}

    - name: Unarchive zip
      ansible.builtin.unarchive:
        src: /tmp/{{ terraform.zip }}
        dest: /usr/local/bin/
        copy: false

  when: terraform_exist.rc != 0 or ( terraform_current_version is defined and terraform_current_version.stdout.find(terraform_version) == -1 )
