- name: install with brew
  homebrew:
    name: "{{ item }}"
    state: installed
  with_items:
    - peco
    - nkf
    - jq
    - awscli
    - coreutils
    - binutils
    - findutils
    # GUI
    - google-chrome
    - vagrant
    - virtualbox
    - slack
    - licecap

- name: install with cask
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items:
    - bitbar
