---
- name: Install with brew
  community.general.homebrew:
    name: "{{ item }}"
    state: installed
  with_items:
    - peco
    - nkf
    - coreutils
    - binutils
    - findutils
    # GUI
    - google-chrome
    - vagrant
    - virtualbox
    - slack
    - licecap
    - imagemagick
    - asciinema
    - agg

- name: Install with cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items:
    - bitbar
