- name: install brew
  homebrew: name={{ item }} state=installed
  with_items:
    - peco
    - nkf
    - jq
    - awscli
    - coreutils
    - binutils
    - findutils
    # GUI
    - google-chrome
    - vagrant
    - virtualbox
    - slack
    - licecap

