---
- name: from source install
  include: source.yml
  when: "ansible_os_family == 'RedHat'"

- name: install zsh
  apt: name=zsh state=present
  when: "ansible_os_family == 'Debian'"

- name: zsh_path
  command: which zsh
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: zsh_path
  changed_when: false

- name: add shells
  lineinfile:
    dest: /etc/shells
    state: present
    line: "{{ zsh_path.stdout }}"

- name: check zsh_completion directory
  stat:
    path: "{{ zsh_completion_dir }}"
  register: exist_zsh_completion

- name: install zsh-completion
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  git:
    repo: "{{ zsh_completion.src }}"
    dest: "{{ zsh_completion_dir }}"
    update: yes
    clone: yes
  when: not exist_zsh_completion.stat.exists

- name: change shell in {{ user }}
  user: name={{ user }} shell={{ zsh_path.stdout }}
