---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  when: ansible_os_family == 'Debian'

- name: Zsh_path
  ansible.builtin.command: which zsh
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: zsh_path
  changed_when: false

- name: Add shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    state: present
    line: "{{ zsh_path.stdout }}"

- name: Change shell in {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ zsh_path.stdout }}"
