---
- name: Install dependency packages
  ansible.builtin.yum:
    name:
      - which
      - ncurses-devel
      - make

- name: Exist zsh
  ansible.builtin.command: which zsh
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: zsh_exist
  changed_when: false
  ignore_errors: true

- name: Get zsh version
  ansible.builtin.command: zsh --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: zsh_current_version
  changed_when: false
  ignore_errors: true
  when: zsh_exist.rc == 0

- name: Check and install
  when: zsh_exist.rc != 0 or ( zsh_current_version is defined and zsh_current_version.stdout.find(zsh_version) == -1 )
  block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ zsh.src }}"
        dest: /tmp/{{ zsh.xz }}
        mode: 0600

    - name: Unarchive tar.xz
      ansible.builtin.command: chdir=/tmp/ tar Jxfv /tmp/{{ zsh.xz }}
      changed_when: true

    - name: Configure make install zsh
      ansible.builtin.command: chdir=/tmp/{{ zsh.dir }} {{ item }}
      changed_when: true
      with_items:
        - ./configure --with-tcsetpgrp
        - make
        - make install
