---
- name: install dependency packages
  yum:
    name:
      - which
      - ncurses-devel
      - make

- name: exist zsh
  command: which zsh
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: exist_zsh
  changed_when: false
  ignore_errors: true

- name: get zsh version
  command: zsh --version
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: version_in_zsh
  changed_when: false
  ignore_errors: true
  when:
    exist_zsh.rc == 0

- block:
    - name: get source
      get_url:
        url: "{{ zsh.src }}"
        dest: /tmp/{{ zsh.xz }}

    - name: unarchive tar.xz
      command: chdir=/tmp/ tar Jxfv /tmp/{{ zsh.xz }}  # noqa 303 xzファイルは未対応のため

    - name: configure make install
      command: chdir=/tmp/{{ zsh.dir }} {{ item }}
      with_items:
        - ./configure --with-tcsetpgrp
        - make
        - make install

  when:
    exist_zsh.rc != 0
    or ( version_in_zsh is defined and version_in_zsh.stdout.find(zsh_version) == -1 )
