---
- name: Exist peco
  ansible.builtin.command: which peco
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_peco
  changed_when: false
  ignore_errors: true

- name: Get peco version
  ansible.builtin.command: peco --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_peco
  changed_when: false
  ignore_errors: true
  when: exist_peco.rc == 0

- block:
    - name: Peco get source
      ansible.builtin.get_url:
        url: "{{ peco.url }}"
        dest: /tmp/{{ peco.tgz }}

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ peco.tgz }}
        dest: /tmp/
        copy: false

    - name: Move peco
      changed_when: true
      ansible.builtin.command: mv /tmp/{{ peco.dir }}/peco /usr/local/bin/peco
  when: exist_peco.rc != 0 or ( version_in_peco is defined and version_in_peco.stderr.find(peco_version) == -1 )
