- name: install anyenv
  git: repo="{{ anyenv.url }}" dest=~/.anyenv

- name: store anyenv profile to zshenv
  lineinfile:
    dest: ~/.zshenv
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - 'export PATH="$HOME/.anyenv/bin:$PATH"'
    - 'eval "$(anyenv init -)"'

- name: "exist {{ item.value.version }}"
  command: which {{ item.key }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH}}"
  register: exist_envs
  changed_when: false
  ignore_errors: true
  with_dict: "{{ envs }}"

- name: "install envs {{ item.0.key }}"
  command: anyenv install {{ item.0.key }}
  when: item.1.rc != 0
  with_together:
    - "{{ envs }}"
    - "{{ exist_envs.results }}"

- name: "store {{ item.key }} to zshenv"
  lineinfile:
    dest: ~/.zshenv
    state: present
    create: yes
    line: 'export PATH="$HOME/.anyenv/envs/{{ item.key }}/shims:$PATH"'
  with_dict: "{{ envs }}"

- name: "exist version {{ item.key }} {{ item.value.version }}"
  shell: "{{ item.key }} versions | grep {{ item.value.version }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH}}"
  register: exist_version
  changed_when: false
  ignore_errors: true
  with_dict: "{{ envs }}"

- name: "install {{ item.0.key }} {{ item.0.value.version }}"
  command: "{{ item.0.key }} install {{ item.0.value.version }}"
  when: item.1.rc != 0
  with_together:
    - "{{ envs }}"
    - "{{ exist_version.results }}"

- name: "exist global {{ item.key }} {{ item.value.version }}"
  command: "{{ item.key }} global"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH}}"
  register: exist_global
  changed_when: false
  ignore_errors: true
  with_dict: "{{ envs }}"

- name: "set global {{ item.0.key }} {{ item.0.value.version }}"
  command: "{{ item.0.key }} global {{ item.0.value.version }}"
  when: item.1.stdout is defined and item.1.stdout.find(item.0.version) == -1
  with_together:
    - "{{ envs }}"
    - "{{ exist_global.results }}"


