---
- name: Redhat tasks
  ansible.builtin.include_tasks: install-glibc.yml
  when: ansible_os_family == 'RedHat'

- name: Exist delta
  ansible.builtin.command: which delta
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_delta
  changed_when: false
  ignore_errors: true

- name: Get delta version
  ansible.builtin.command: delta --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_delta
  changed_when: false
  ignore_errors: true
  when: exist_delta.rc == 0

- block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ delta.src }}"
        dest: /tmp/{{ delta.tgz }}

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ delta.tgz }}
        dest: /tmp/
        copy: false

    - name: Move delta
      changed_when: true
      ansible.builtin.command: mv /tmp/{{ delta.dir }}/delta /usr/local/bin/delta
  when: exist_delta.rc != 0 or ( version_in_delta is defined and version_in_delta.stdout.find(delta_version) == -1 )
