---
- name: Exist agg  # noqa command-instead-of-shell
  ansible.builtin.shell: command -v agg
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: agg_exist
  changed_when: false
  ignore_errors: true

- name: Get agg version
  ansible.builtin.shell: echo "v$(agg --version | head -n 1 | awk '{print $2}')"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: agg_current_version
  changed_when: false
  ignore_errors: true
  when: agg_exist.rc == 0

- name: Install
  when: agg_exist.rc != 0 or ( agg_current_version is defined and agg_current_version.stdout.find(agg_version) == -1 agg_version)
  ansible.builtin.get_url:
    url: "{{ agg.src.linux }}"
    dest: /usr/local/bin/agg
    mode: "0755"
