---
- name: Exist fillin
  ansible.builtin.command: which fillin
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: fillin_exist
  changed_when: false
  ignore_errors: true

- name: Get fillin version
  ansible.builtin.command: fillin -v
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: fillin_current_version
  changed_when: false
  ignore_errors: true
  when: fillin_exist.rc == 0

- name: Check and install
  block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ fillin.src }}"
        dest: /tmp/{{ fillin.tgz }}

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ fillin.tgz }}
        dest: /tmp/
        copy: false

    - name: Move fillin
      changed_when: true
      ansible.builtin.command: mv /tmp/{{ fillin.dir }}/fillin /usr/local/bin/fillin
  when: fillin_exist.rc != 0 or ( fillin_current_version is defined and fillin_current_version.stdout.find(fillin_version) == -1 )
