- name: install apt-packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - bash-completion
    - gcc
    - make
    - tar
    - zsh
    - zlib
    - unzip
    - dos2unix
    - openssl
    - ctags
    - nkf

