- name: install epel-release
  yum: name=epel-release state=installed

- name: install packages
  yum: name={{ item }} state=installed
  with_items:
    - curl-devel
    - bash-completion
    - patch
    - wget
    - gcc
    - gcc-c++
    - bc
    - mlocate
    - tar
    - unzip
    - dos2unix
    - unix2dos
    - openssl-devel
    - readline-devel
    - the_silver_searcher
    - lsof
    - dstat
    - tcpdump
    - python-devel
    - ctags
    - sqlite-devel
    - inotify-tools
    - ansible

- name: install rpmforge
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el{{ ansible_distribution_major_version }}/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el{{ ansible_distribution_major_version }}/mirrors-rpmforge
    enabled: no

- name: set timezone to Asia/Tokyo
  file:
    src: /usr/share/zoneinfo/Japan
    dest: /etc/localtime
    state: link

- name: disable SELinux
  selinux: state=disabled

# add '/usr/local/bin' into PATH
- name: set profile.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/profile.d/{{ item }}.sh"
    mode: 0755
  with_items:
    - path

- name: set path to zshenv
  template:
    src: path.j2
    dest: /etc/zshenv
    mode: 0755

- name: edit suduers
  replace:
    dest: /etc/sudoers
    regexp: 'secure_path = /sbin:/bin:/usr/sbin:/usr/bin$'
    replace: 'secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'

- name: enable ipv4 forward for docker
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: "net.ipv4.ip_forward=1"

- name: ncrease max_map_count. for docker[elasticsearch5]
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: "vm.max_map_count=262144"


