---
# add '/usr/local/bin' into PATH
- name: Set profile.d
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/profile.d/{{ item }}.sh
    mode: "0755"
  with_items:
    - path

- name: Set path to zshenv
  ansible.builtin.template:
    src: path.j2
    dest: /etc/zshenv
    mode: "0755"

- name: Edit suduers
  ansible.builtin.replace:
    dest: /etc/sudoers
    regexp: secure_path = /sbin:/bin:/usr/sbin:/usr/bin$
    replace: secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"

- name: Enable ipv4 forward for docker
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: net.ipv4.ip_forward=1
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"

- name: Ncrease max_map_count. for docker[elasticsearch5]
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: vm.max_map_count=262144
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"
