---
- name: debian tasks
  include: debian.yml
  when: "ansible_os_family == 'Debian'"

- name: redhat tasks
  include: redhat.yml
  when: "ansible_os_family == 'RedHat'"

# add '/usr/local/bin' into PATH
- name: set profile.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/profile.d/{{ item }}.sh"
    mode: 0755
  with_items:
    - path

- name: set path to zshenv
  template:
    src: path.j2
    dest: /etc/zshenv
    mode: 0755

- name: edit suduers
  replace:
    dest: /etc/sudoers
    regexp: 'secure_path = /sbin:/bin:/usr/sbin:/usr/bin$'
    replace: 'secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
  when: ansible_env.has_key('CI') and ansible_env.CI != "true"

- name: enable ipv4 forward for docker
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: "net.ipv4.ip_forward=1"
  when: ansible_env.has_key('CI') and ansible_env.CI != "true"

- name: ncrease max_map_count. for docker[elasticsearch5]
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: "vm.max_map_count=262144"
  when: ansible_env.has_key('CI') and ansible_env.CI != "true"
