---
- name: install epel-release
  yum: name=epel-release state=installed

- name: install packages
  yum:
    name:
      - nkf
      - curl-devel
      - bash-completion
      - patch
      - wget
      - gcc
      - gcc-c++
      - bc
      - mlocate
      - tar
      - unzip
      - dos2unix
      - unix2dos
      - openssl-devel
      - readline-devel
      - the_silver_searcher
      - lsof
      - dstat
      - tcpdump
      - python-devel
      - ctags
      - sqlite-devel
      - inotify-tools
      - ansible
      - vsftpd
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - bzip2-devel
      - Xvfb
      - libgconf-2.so.4
      - GConf2
      - make
      - libffi-devel
    state: installed

- name: install rpmforge
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el{{ ansible_distribution_major_version }}/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el{{ ansible_distribution_major_version }}/mirrors-rpmforge
    enabled: no

- name: set timezone to Asia/Tokyo
  file:
    src: /usr/share/zoneinfo/Japan
    dest: /etc/localtime
    state: link

- name: disable SELinux
  selinux: state=disabled
  when: ansible_env.has_key('CI') and ansible_env.CI != "true"
