---
- name: directory
  file:
    path: /usr/share/fonts/noto
    state: directory
    owner: root
    group: root
    mode: 0755

- name: get zip
  get_url:
    url: "{{ notofont.src }}"
    dest: "/tmp/{{ notofont.zip }}"

- name: unarchive zip
  unarchive:
    src: "/tmp/{{ notofont.zip }}"
    dest: /usr/share/fonts/noto/
    copy: no

- name: change permission file list
  find:
    paths: /usr/share/fonts/noto/
    patterns: "*.otf"
  register: otf_files

- name: change permission
  file:
    path: "{{ item.path }}"
    mode: 0644
  with_items:
    - "{{ otf_files.files }}"

- name: font-cache
  command:
    cmd: fc-cache -fv
    creates: /usr/share/fonts/noto/*.otf
