---
- name: Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Redhat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
