---
- name: Install epel-release
  ansible.builtin.yum:
    name: epel-release
    state: installed
- name: Install packages
  ansible.builtin.yum:
    name:
      - nkf
      - curl-devel
      - bash-completion
      - patch
      - wget
      - gcc
      - gcc-c++
      - bc
      - mlocate
      - tar
      - unzip
      - dos2unix
      - unix2dos
      - openssl-devel
      - the_silver_searcher
      - lsof
      - dstat
      - tcpdump
      - ctags
      - sqlite-devel
      - inotify-tools
      - ansible
      - vsftpd
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - Xvfb
      - libgconf-2.so.4
      - GConf2
      - make
      - which
      - libffi-devel
      - ImageMagick
    state: installed

- name: Install rpmforge
  ansible.builtin.yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el{{ ansible_distribution_major_version }}/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el{{ ansible_distribution_major_version }}/mirrors-rpmforge
    enabled: false

- name: Set timezone to Asia/Tokyo
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Japan
    dest: /etc/localtime
    state: link

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"
