---
- name: Exist awscli v2
  ansible.builtin.command: which aws
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: awscli_exist
  changed_when: false
  ignore_errors: true

- name: Get awscli version
  ansible.builtin.shell: "aws --version 2>&1 | grep -oP '(?<=aws-cli\\/)\\d+\\.\\d+\\.\\d+' "
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: awscli_current_version
  changed_when: false
  ignore_errors: true
  when: awscli_exist.rc == 0

- name: Check and install
  when: awscli_exist.rc != 0 or ( awscli_current_version is defined and awscli_current_version.stdout.find(awscli_version) == -1 )
  block:
    - name: Get zip
      ansible.builtin.get_url:
        url: "{{ awscli.src }}"
        dest: /tmp/{{ awscli.zip }}
        mode: 0600

    - name: Unarchive zip
      ansible.builtin.unarchive:
        src: /tmp/{{ awscli.zip }}
        dest: /tmp/
        copy: false

    - name: Install
      changed_when: true
      ansible.builtin.command:
        cmd: ./aws/install --update
        chdir: /tmp
