---
- name: Vim8 redhat dependencies
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name:
      - python-devel
      - lua-devel
      - perl-ExtUtils-Embed
      - make
      - ncurses-devel
    state: present

- name: Vim8 install dependencies package
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name:
      - libncurses-dev
      - libperl-dev
    state: present

- name: Exist vim
  ansible.builtin.command: which vim
  register: exist_vim
  changed_when: false
  ignore_errors: true

- name: Get vim major version
  ansible.builtin.shell: vim --version | grep IMproved
  register: version_in_vim
  changed_when: false
  ignore_errors: true
  when: exist_vim.rc == 0

- name: Get vim patch version
  ansible.builtin.shell: vim --version | grep 'Included patches:'
  register: patch_version_in_vim
  changed_when: false
  ignore_errors: true
  when: exist_vim.rc == 0

- block:
    - name: Install vim
      environment:
        PATH: /usr/local/bin:{{ ansible_env.PATH }}
      ansible.builtin.script: install.sh v{{ vim_version }}
  when: exist_vim.rc != 0 or ( version_in_vim is defined and version_in_vim.stdout.find(".".join(vim_version.split('.')[0:2])) == -1) or ( patch_version_in_vim is
    defined and patch_version_in_vim.stdout.find(vim_version.split('.')[2]) == -1)
