---
- name: exist vim
  command: which vim
  register: exist_vim
  changed_when: false
  ignore_errors: true

- name: get vim major version
  shell: vim --version | grep IMproved
  register: version_in_vim
  changed_when: false
  ignore_errors: true
  when:
    exist_vim.rc == 0

- name: get vim patch version
  shell: vim --version | grep 'Included patches:'
  register: patch_version_in_vim
  changed_when: false
  ignore_errors: true
  when:
    exist_vim.rc == 0

- block:
    - name: install vim
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      script: "install.sh v{{ vim_version }}"
  when:
    exist_vim.rc != 0
    or ( version_in_vim is defined and version_in_vim.stdout.find(".".join(vim_version.split('.')[0:2])) == -1)
    or ( patch_version_in_vim is defined and patch_version_in_vim.stdout.find(vim_version.split('.')[2]) == -1)
