---
- name: exist vim
  command: which vim
  register: exist_vim
  changed_when: false
  ignore_errors: true

- name: get vim major version
  shell: vim --version | grep IMproved
  register: version_in_vim
  changed_when: false
  ignore_errors: true
  when:
    exist_vim.rc == 0

- name: get vim patch version
  shell: vim --version | grep 'Included patches:'
  register: patch_version_in_vim
  changed_when: false
  ignore_errors: true
  when:
    exist_vim.rc == 0

- block:
    - name: install packages
      yum: name={{ item }} state=installed
      with_items:
        - git
        - lua-devel
        - perl-ExtUtils-Embed
        - make
        - ncurses-devel
    - name: install vim
      script: "install.sh v{{ vim_version }}.{{ vim_version_patch }}"
  when:
    exist_vim.rc != 0
    or ( version_in_vim is defined and version_in_vim.stdout.find(vim_version) == -1)
    or ( patch_version_in_vim is defined and patch_version_in_vim.stdout.find(vim_version_patch) == -1)
