---
- name: Install global tools  # noqa command-instead-of-shell
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  ansible.builtin.shell: "{{ execute }} 'mise -y i'"
  changed_when: true
