---
- name: cat
  ansible.builtin.shell: "{{ execute }} 'cat ~/.config/mise/config.toml'"
  register: fuga

- name: debug
  debug:
    msg: "{{ fuga }}"

- name: Check mise tools  # noqa command-instead-of-shell
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  ansible.builtin.shell: "{{ execute }} 'mise config get'"
  changed_when: true
  register: hoge

- name: debug
  debug:
    msg: "{{ hoge }}"

- name: Install global tools  # noqa command-instead-of-shell
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  ansible.builtin.shell: "{{ execute }} 'mise -y i {{ ansible_env.get('TOOLS', '') }}'"
  changed_when: true
