---
- name: Exist jq
  ansible.builtin.command: which jq
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: jq_exist
  changed_when: false
  ignore_errors: true

- name: Get jq version
  ansible.builtin.command: jq --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: jq_current_version
  changed_when: false
  ignore_errors: true
  when: jq_exist.rc == 0

- name: Check and install
  block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ jq.src }}"
        dest: /usr/local/bin/jq
        mode: "0755"

  when: jq_exist.rc != 0 or ( jq_current_version is defined and jq_current_version.stdout.find(jq_version) == -1 )
