---
- name: Language dependencies in Debian
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.apt:
    name:
      - libssl-dev
      - libyaml-dev
      - libgdbm-dev
      - libgdbm-compat-dev
      - liblzma-dev
      - xz-utils
      - libncurses5-dev
      - libreadline6-dev
      - lzma
      - lzma-dev
      - tk-dev
      - uuid-dev
      - python3.12-venv
    state: present
