---
- name: Anyenv redhat dependencies
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name:
      - openssl-devel
      - readline-devel
      - bzip2
      - tar
    state: present

- name: Anyenv dependencies package
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.apt:
    name:
      - libssl-dev
      - libyaml-dev
      - libgdbm-dev
      - libgdbm-compat-dev
      - liblzma-dev
      - xz-utils
      - libncurses5-dev
      - libreadline6-dev
      - lzma
      - lzma-dev
      - tk-dev
      - uuid-dev
    state: present
