---
- name: Exist tmux
  ansible.builtin.command: which tmux
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: tmux_exist
  changed_when: false
  ignore_errors: true

- name: Get tmux version
  ansible.builtin.command: tmux -V
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: tmux_current_version
  changed_when: false
  ignore_errors: true
  when: tmux_exist.rc == 0

- name: Install dependencies package
  ansible.builtin.apt:
    name: [bison, libevent-dev, libncurses-dev]
    state: present

- name: Get source
  ansible.builtin.get_url:
    url: "{{ tmux.src }}"
    dest: /tmp/{{ tmux.tgz }}
    mode: 0600

- name: Unarchive tar.gz
  ansible.builtin.unarchive:
    src: /tmp/{{ tmux.tgz }}
    dest: /tmp
    copy: false

- name: Configure make install tmux
  changed_when: true
  ansible.builtin.command:
    chdir: /tmp/{{ tmux.dir }}
    cmd: "{{ item }}"
  with_items:
    - ./configure
    - make
    - make install
