---
- name: Exist direnv
  ansible.builtin.command: which direnv
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: direnv_exist
  changed_when: false
  ignore_errors: true

- name: Get direnv version
  ansible.builtin.command: direnv --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: direnv_current_version
  changed_when: false
  ignore_errors: true
  when: direnv_exist.rc == 0

- block:
    - name: Get source
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: "{{ direnv.src }}"
        dest: /usr/local/bin/direnv
        mode: "0755"

  when: direnv_exist.rc != 0 or ( direnv_current_version is defined and direnv_current_version.stdout.find(direnv_version) == -1 )

- name: Store direnv hook to zshenv
  ansible.builtin.lineinfile:
    dest: ~/.zshenv
    state: present
    create: true
    line: "{{ item }}"
    mode: "0644"
  with_items:
    - eval "$(direnv hook zsh)"
