link:
  zsh:
    dest_dir: ~/.anyenv/envs/pyenv/versions/{{ envs.pyenv.version }}/lib/python{{ envs.pyenv.version.rsplit('.',1).pop(0) }}/site-packages/powerline/config_files/colorschemes
    dest_file: default.json
