powerline_dir: ~/.anyenv/envs/pyenv/versions/{{ envs.pyenv.version }}/lib/python{{ envs.pyenv.version.rsplit('.',1).pop(0) }}/site-packages/powerline
link:
  zsh:
    dest_dir: "{{ powerline_dir }}/config_files/colorschemes"
    dest_file: default.json
  tmux:
    basedir: "{{ powerline_dir }}/bindings/tmux"
    files:
      - powerline-base.conf
      - powerline.conf


