---
- name: Exist docker_compose
  ansible.builtin.command: which docker-compose
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: docker_compose_exist
  changed_when: false
  ignore_errors: true

- name: Get docker_compose version
  ansible.builtin.command: docker-compose --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: docker_compose_current_version
  changed_when: false
  ignore_errors: true
  when: docker_compose_exist.rc == 0

- name: Check and install
  block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ docker_compose.src }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

  when: docker_compose_exist.rc != 0 or ( docker_compose_current_version is defined and docker_compose_current_version.stdout.find(docker_compose_version) == -1 )
