- name: exist docker_compose
  command: which docker_compose
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH}}"
  register: exist_docker_compose
  changed_when: false
  ignore_errors: true

- name: get docker_compose version
  shell: docker_compose --version
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH}}"
  register: version_in_docker_compose
  changed_when: false
  ignore_errors: true
  when:
    exist_docker_compose.rc == 0

- block:
  - name: get source
    get_url:
      url: "{{ docker_compose.src }}"
      dest: /usr/local/bin/docker-compose
      mode: 0755

  when:
    exist_docker_compose.rc != 0
    or ( version_in_docker_compose is defined and version_in_docker_compose.stdout.find(docker_compose_version) == -1 )

- name: get docker-compose completion in bash
  get_url:
    url: "{{ docker_compose_completion.bash }}"
    dest: /etc/bash_completion.d/docker-compose
    mode: 0755

- name: get docker-compose completion in zsh
  get_url:
    url: "{{ docker_compose_completion.zsh }}"
    dest: "{{ zsh_completion_dir }}/src/_docker-compose"
    mode: 0755

