- name: symlink dotfiles
  file:
    src: "{{ dotfiles.dest }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ dotfiles.files }}"

- name: symlink zsh color theme
  file:
    src: "{{ dotfiles.dest }}/zsh/.color.{{ zsh_color }}"
    dest: "~/.zshrc.color"
    state: link
  when: zsh_color is defined
  tags:
    - color

- name: symlink zsh color theme for powerline(custom)
  file:
    src: "{{ dotfiles.dest }}/powerline_theme/shell_colorscheme_{{ zsh_color }}.json"
    dest: "{{ link.zsh.dest_dir }}/shell/{{ link.zsh.dest_file }}"
    state: link
    force: yes
  when: zsh_color is defined and zsh_color != 'soralized'
  tags:
    - color

- name: symlink zsh color theme for powerline(soralized)
  file:
    src: "{{ link.zsh.dest_dir }}/shell/soralized.json"
    dest: "{{ link.zsh.dest_dir }}/shell/{{ link.zsh.dest_file }}"
    state: link
    force: yes
  when: zsh_color is defined and zsh_color == 'soralized'
  tags:
    - color

- name: symlink tmux powerline config
  file:
    src: "{{ link.tmux.basedir }}/{{ item }}"
    dest: "~/.tmux-{{ item }}"
    state: link
    force: yes
  with_items: "{{ link.tmux.files }}"

# TODO tmuxのカラー設定

# TODO vimの設定へのリンク

# TODO soralizedの追加


