- name: upgrade pip
  pip: name=pip state=latest

- name: install powerline
  pip: name="{{ item }}" state=present editable=false
  with_items:
    - "git+git://github.com/powerline/powerline"
    - psutil
