---
- name: Upgrade pip
  ansible.builtin.pip: name=pip
- name: Install powerline # noqa no-changed-when
  # FIXME not idempotency because install login user. but not loaded zshenv via pip module
  # pip: name="{{ item }}" state=present editable=false
  ansible.builtin.shell: "{{ execute }} pip install {{ item }}"
  with_items:
    - psutil
    - --upgrade git+git://github.com/powerline/powerline
