---
- name: Install apt-packages
  ansible.builtin.apt:
    name:
      - make
      - gcc
      - zlib1g-dev
      - gettext
      - autoconf
      - asciidoc
      - libcurl4-openssl-dev
    update_cache: yes
    state: present
