---
- name: Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Redhat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Exist git
  ansible.builtin.command: which git
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: git_exist
  changed_when: false
  ignore_errors: true

- name: Get git version  # noqa command-instead-of-module
  ansible.builtin.command: git --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: git_current_version
  changed_when: false
  ignore_errors: true
  when: git_exist.rc == 0

- name: Check and install
  when: git_exist.rc != 0 or ( git_current_version is defined and git_current_version.stdout.find(git_version.replace("v","")) == -1 )
  block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ git.src }}"
        dest: /tmp/{{ git.tgz }}
        mode: 0600

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ git.tgz }}
        dest: /tmp
        copy: false

    - name: Configure make install git
      ansible.builtin.command: chdir=/tmp/{{ git.dir }} {{ item }}
      changed_when: true
      with_items:
        - ./configure
        - make
        - make install
