---
- name: Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Redhat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Exist git
  ansible.builtin.command: which git
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_git
  changed_when: false
  ignore_errors: true

- name: Get git version # noqa command-instead-of-module
  ansible.builtin.command: git --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_git
  changed_when: false
  ignore_errors: true
  when: exist_git.rc == 0

- block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ git.src }}"
        dest: /tmp/{{ git.tgz }}

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ git.tgz }}
        dest: /tmp
        copy: false

    - name: Configure make install git
      ansible.builtin.command: chdir=/tmp/{{ git.dir }} {{ item }}
      changed_when: true
      with_items:
        - ./configure
        - make
        - make install

  when: exist_git.rc != 0 or ( version_in_git is defined and version_in_git.stdout.find(git_version.replace("v","")) == -1 )
