---
- name: dependencies packages
  yum:
    name:
      - make
      - perl-ExtUtils-MakeMaker
      - zlib-devel
      - curl-devel
      - tcl
      - gettext

- name: latest packages
  yum:
    name:
      - ca-certificates
    state: latest
