---
- name: Dependencies packages
  ansible.builtin.yum:
    name:
      - make
      - perl-ExtUtils-MakeMaker
      - zlib-devel
      - curl-devel
      - tcl
      - gettext

- name: Latest packages
  ansible.builtin.yum:
    name:
      - ca-certificates
    state: latest  # noqa package-latest
