---
- name: Install repository
  ansible.builtin.yum:
    name: "{{ nginx.repo }}"
    state: installed

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
    disable_gpg_check: true
