---
- name: Exist reviewdog # noqa command-instead-of-shell
  ansible.builtin.shell: command -v reviewdog
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_reviewdog
  changed_when: false
  ignore_errors: true

- name: Get reviewdog version
  ansible.builtin.command: reviewdog --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_reviewdog
  changed_when: false
  ignore_errors: true
  when: exist_reviewdog.rc == 0

- block:
    - name: Get tar.gz
      ansible.builtin.get_url:
        url: "{{ reviewdog.src.darwin }}"
        dest: /tmp/{{ reviewdog.tgz }}
      when: ansible_os_family == 'Darwin'

    - name: Get tar.gz
      ansible.builtin.get_url:
        url: "{{ reviewdog.src.linux }}"
        dest: /tmp/{{ reviewdog.tgz }}
      when: ansible_os_family != 'Darwin'

    - name: Unarchive zip
      ansible.builtin.unarchive:
        src: /tmp/{{ reviewdog.tgz }}
        dest: /tmp/
        copy: false

    - name: Install
      changed_when: true
      ansible.builtin.command: mv /tmp/reviewdog /usr/local/bin/reviewdog
  when: exist_reviewdog.rc != 0 or ( version_in_reviewdog is defined and version_in_reviewdog.stdout.find(reviewdog_version) == -1 )
