---
- name: Get source
  ansible.builtin.get_url:
    url: "{{ bat.deb }}"
    dest: /tmp/bat-{{ bat_version }}.deb

- name: Install bat
  ansible.builtin.apt:
    deb: /tmp/bat-{{ bat_version }}.deb
