---
- name: Exist bat
  ansible.builtin.command: which bat
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_bat
  changed_when: false
  ignore_errors: true

- name: Get bat version
  ansible.builtin.command: bat --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_bat
  changed_when: false
  ignore_errors: true
  when: exist_bat.rc == 0

- block:
    - name: Debian tasks
      ansible.builtin.include_tasks: debian.yml
      when: ansible_os_family == 'Debian'

    - name: Redhat install tasks
      ansible.builtin.include_tasks: redhat.yml
      when: ansible_os_family == 'RedHat'

  when: exist_bat.rc != 0 or ( version_in_bat is defined and version_in_bat.stdout.find(bat_version) == -1 )
