---
- name: Exist bat
  ansible.builtin.command: which bat
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: bat_exist
  changed_when: false
  ignore_errors: true

- name: Get bat version
  ansible.builtin.command: bat --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: bat_current_version
  changed_when: false
  ignore_errors: true
  when: bat_exist.rc == 0

- name: Check and install
  block:
    - name: Debian tasks
      ansible.builtin.include_tasks: debian.yml
      when: ansible_os_family == 'Debian'

    - name: Redhat install tasks
      ansible.builtin.include_tasks: redhat.yml
      when: ansible_os_family == 'RedHat'

  when: bat_exist.rc != 0 or ( bat_current_version is defined and bat_current_version.stdout.find(bat_version) == -1 )
