---
- name: Get source
  ansible.builtin.get_url:
    url: "{{ bat.src }}"
    dest: /tmp/{{ bat.tgz }}

- name: Unarchive tar.gz
  ansible.builtin.unarchive:
    src: /tmp/{{ bat.tgz }}
    dest: /tmp/
    copy: false

- name: Copy to bin
  ansible.builtin.copy:
    remote_src: true
    mode: "0755"
    src: /tmp/{{ bat.dir }}/bat
    dest: /usr/local/bin/bat
