---
- name: Exist docker
  ansible.builtin.command: which docker
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: docker_exist
  changed_when: false
  ignore_errors: true

- name: Get docker version
  ansible.builtin.command: docker --version
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: docker_current_version
  changed_when: false
  ignore_errors: true
  when: docker_exist.rc == 0

- name: Check and install
  block:
    - name: Download repo
      changed_when: true
      ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install
      ansible.builtin.yum:
        name: docker-ce
        state: installed

    - name: Docker start and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      when: ansible_env.get('CI', None) and ansible_env.CI != "true"

  when: docker_exist.rc != 0 or ( docker_current_version is defined and docker_current_version.stdout.find(docker_version) == -1 )
