---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - { role: common, tags: [common, init, tool] }
    - { role: git, tags: [git, init, tool, deploy] }
    - { role: chrome, tags: [chrome, tool] }
    - { role: zsh, tags: [zsh, init] }
    - { role: jo, tags: [jo, tool] }
    - { role: peco, tags: [peco, init] }
    - { role: bat, tags: [bat, tool] }
    - { role: jq, tags: [jq, init] }
    - { role: docker-compose, tags: [docker-compose, init] }
    - { role: terraform, tags: [terraform, tool] }
    - { role: embulk, tags: [embulk, tool] }
    - { role: sshrc, tags: [sshrc, tool] }
    - { role: vim8, tags: [vim8, init] }
    - { role: tmux, tags: [tmux, init] }
    - { role: docker, tags: [docker, init] }
    - { role: samba, tags: [samba, tool] }
    - { role: q, tags: [q, tool] }
    - { role: nginx, tags: [nginx, tool] }
    - { role: notofont, tags: [notofont, init] }
    - { role: by_pip, tags: [by_pip, init] }  # cheat, mycli, awscli

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: no
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
    # to bin and install languages
    - { role: anyenv, tags: [anyenv, init] }
    - { role: direnv, tags: [direnv, init]}
    - { role: powerline, tags: [powerline, init] }
    - { role: zsh_syntax_highlighting, tags: [zsh_syntax_highlighting, init] }
    - { role: vim-plugins, tags: [vim-plugins, init] }
