---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: true
  roles:
    - { role: packages, tags: [common, init, tool, dev] }
    - { role: language-dependencies, tags: [anyenv] }
    - { role: common, tags: [common, init, tool, anyenv] }
    - { role: git, tags: [git, init, tool, deploy, anyenv] }
    - { role: zsh, tags: [zsh, init, anyenv] }
    - { role: jo, tags: [jo, tool] }
    - { role: peco, tags: [peco, init] }
    - { role: bat, tags: [bat, tool] }
    - { role: delta, tags: [delta] }
    - { role: jq, tags: [jq, init] }
    - { role: docker-compose, tags: [docker-compose, dev] }
    - { role: terraform, tags: [terraform, tool] }
    - { role: embulk, tags: [embulk, tool] }
    - { role: awscli, tags: [awscli, tool] }
    - { role: fillin, tags: [fillin, tool] }
    # - { role: sshrc, tags: [sshrc, tool] }
    - { role: vim8, tags: [vim8, vim] }
    - { role: tmux, tags: [tmux, init] }
    - { role: docker, tags: [docker, dev] }
    - { role: samba, tags: [samba, tool] }
    - { role: q, tags: [q, tool] }
    - { role: nginx, tags: [nginx, dev] }
    - { role: notofont, tags: [notofont, init] }
    - { role: by_pip, tags: [by_pip, tool] } # cheat, mycli
    - { role: actionlint, tags: [actionlint, tool] }
    - { role: reviewdog, tags: [reviewdog, tool] }

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: false
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
    # to bin and install languages
    - { role: anyenv, tags: anyenv }
    # - { role: direnv, tags: [direnv, init]}
    - { role: powerline, tags: [powerline, init] }
    - { role: vim-plugins, tags: [vim-plugins, vim] }
