---
- name: Play for Codespace(root)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: true
  roles:
    - { role: common, tags: [common, init, tool] }
    - { role: peco, tags: [peco, init] }
    - { role: tmux, tags: [tmux, init] }
    - { role: notofont, tags: [notofont, init] }
    - { role: actionlint, tags: [actionlint, tool] }
    - { role: reviewdog, tags: [reviewdog, tool] }

- name: Play for Codespace(User)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: false
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
