---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: yes
  roles:
    - { role: common, tags: [common, init, tool] }
    - { role: peco, tags: [peco, init] }
    - { role: jq, tags: [jq, init] }
    - { role: tmux, tags: [tmux, init] }
    - { role: bat, tags: [bat, tool] }
    - { role: delta, tags: [delta, tool] }
    - { role: notofont, tags: [notofont, init] }
    - { role: awscli, tags: [awscli, tool] }
    - { role: actionlint, tags: [actionlint, tool] }

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: no
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
