---
# local config
user: vagrant
git_username: swfz
git_usermail: sawafuji.09@gmail.com
git_editor: vim
envs:
  # plenv:
  #   { version: 5.26.2 }
  rbenv:
    { version: 2.6.5 }
  pyenv:
    { version: 3.8.1 }
  nodenv:
    { version: 13.5.0 }
  goenv:
    { version: 1.12.7 }

dotfiles:
  src:
    repo: http://github.com/swfz/dotfiles.git
  dest: ~/dotfiles
  files:
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .agignore
    - .sshrc
    - .darwin.rc
    - .gvimrc
git_hooks:
  src:
    repo: http://github.com/swfz/git-hooks.git
  dest: ~/git-hooks

command_dir: ~/bin
execute: "$(command -v zsh) -lc"
