# local config
user: vagrant
git_username: swfz
git_usermail: sawafuji.09@gmail.com
git_editor: vim
envs:
  plenv:
    { version: 5.25.2 }
  rbenv:
    { version: 2.4.2 }
  pyenv:
    { version: 3.5.2 }
  ndenv:
    { version: v9.11.1 }
  goenv:
    { version: 1.10.2 }

dotfiles:
  src:
    repo: http://github.com/swfz/dotfiles.git
  dest: ~/dotfiles
  files:
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .agignore
    - .sshrc

command_dir: ~/bin
zsh_completion_dir: /etc/zsh_completion.d
bash_completion_dir: /etc/bash_completion.d
execute: /usr/local/bin/zsh -lc

# root config
git_version: '2.17.0'
tmux_version: '2.7'
peco_version: 'v0.5.3'
zsh_version: '5.2'
jq_version: '1.5'
jo_version: '1.0'
q_version: '1.5.0-1'
docker_version: '1.10.3'
docker_compose_version: '1.21.2'
apex_version: '0.11.0'
terraform_version: '0.11.7'
embulk_version: '0.9.7'


