# local config
user: vagrant
git_username: swfz
git_usermail: sawafuji.09@gmail.com
git_editor: vim
envs:
  # plenv:
  #   { version: 5.26.2 }
  rbenv:
    { version: 2.6.0 }
  pyenv:
    { version: 3.6.6 }
  nodenv:
    { version: 12.6.0 }
  goenv:
    { version: 1.12.7 }

dotfiles:
  src:
    repo: http://github.com/swfz/dotfiles.git
  dest: ~/dotfiles
  files:
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .agignore
    - .sshrc

command_dir: ~/bin
zsh_completion_dir: /etc/zsh_completion.d
bash_completion_dir: /etc/bash_completion.d
execute: "$(which zsh) -lc"

# root config
vim_version: '8.1'
vim_version_patch: '2124'
git_version: '2.24.1'
tmux_version: '2.8'
peco_version: 'v0.5.3'
zsh_version: '5.2'
jq_version: '1.6'
jo_version: '1.0'
q_version: '1.7.1-1'
docker_version: '18.09'
docker_compose_version: '1.23.2'
apex_version: '0.16.0'
terraform_version: '0.11.11'
embulk_version: '0.9.11'
direnv_version: 'v2.20.0'
