---
- hosts: local
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - common
    # ========== from source to build ==========
    - git
    - zsh
    - jo
    # ========== from source to bin ==========
    - peco
    - jq
    - docker-compose
    # ========== yum ==========
    - tmux
    - docker
    - samba
    - q
    - nginx
    # ========== pip ==========
    - by_pip # cheat, mycli
    # TODO
    # - apex
    # - terraform
    # - aws cli

- hosts: local
  vars_files:
    - common_vars.yml
  become_user: "{{ user }}"
  roles:
    - config
    # to bin and install languages
    - anyenv
    # TODO
    - powerline
    - zsh_syntax_highlighting
    # - envfile
    # - enhanced
    # - link
    # - vim_plugins


