---
- hosts: local
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - common
    # ========== from source to build ==========
    - git
    - zsh
    - jo
    # ========== from source to bin ==========
    - peco
    - jq
    - docker-compose
    - terraform
    - embulk
    # execute install.sh
    - apex
    # ========== yum ==========
    - tmux
    - docker
    - samba
    - q
    - nginx
    # ========== pip ==========
    - by_pip # cheat, mycli, awscli

- hosts: local
  # strategy: debug
  vars_files:
    - common_vars.yml
  become_user: "{{ user }}"
  roles:
    - preconfig
    # to bin and install languages
    - anyenv
    - powerline
    - zsh_syntax_highlighting
    # TODO
    # - envfile
    # - enhanced
    # - vim_plugins
    - postconfig


