---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - { role: common, tags: common }
    # ========== from source to build ==========
    - { role: git, tags: git }
    - { role: zsh, tags: zsh }
    - { role: jo, tags: jo }
    # ========== from source to bin ==========
    - { role: peco, tags: peco }
    - { role: jq, tags: jq }
    - { role: docker-compose, tags: docker-compose }
    - { role: terraform, tags: terraform }
    - { role: embulk, tags: embulk }
    - { role: sshrc, tags: sshrc }
    # ========== yum ==========
    - { role: vim8, tags: vim8 }
    - { role: tmux, tags: tmux }
    - { role: docker, tags: docker }
    - { role: samba, tags: samba }
    - { role: q, tags: q }
    - { role: nginx, tags: nginx }
    # ========== pip ==========
    - { role: notofont, tags: notofont }
    - { role: by_pip, tags: by_pip }  # cheat, mycli, awscli

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: no
  become_user: "{{ user }}"
  roles:
    - { role: preconfig, tags: preconfig }
    # to bin and install languages
    - { role: anyenv, tags: anyenv }
    - { role: direnv, tags: direnv}
    - { role: powerline, tags: powerline }
    - { role: zsh_syntax_highlighting, tags: zsh_syntax_highlighting }
    - { role: postconfig, tags: postconfig }
