FROM ubuntu:noble@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b

RUN apt-get update \
    export DEBIAN_FRONTEND=noninteractive \
    apt-get install -y software-properties-common gpg-agent curl sudo tzdata \
    add-apt-repository ppa:deadsnakes/ppa -y \
    apt-get update \
    apt-get install -y python3.12 python3.12-venv \
    curl -LsSf https://astral.sh/uv/install.sh | sh \
    mv ~/.local/bin/uv /usr/local/bin/uv \
    uv venv --python python3.12 \
    uv pip install --no-cache ansible ansible-lint

WORKDIR /app

