FROM ubuntu:resolute@sha256:b7f48194d4d8b763a478a621cdc81c27be222ba2206ca3ca6bc42b49685f3d9e

RUN apt-get update \
    export DEBIAN_FRONTEND=noninteractive \
    apt-get install -y software-properties-common gpg-agent curl sudo tzdata \
    add-apt-repository ppa:deadsnakes/ppa -y \
    apt-get update \
    apt-get install -y python3.12 python3.12-venv \
    curl -LsSf https://astral.sh/uv/install.sh | sh \
    mv ~/.local/bin/uv /usr/local/bin/uv \
    uv venv --python python3.12 \
    uv pip install --no-cache ansible ansible-lint

WORKDIR /app

