FROM ubuntu:resolute@sha256:53958ec7b67c2c9355df922dd08dbf0360611f8c3cdb656875e81873db9ffdba

RUN apt-get update \
    export DEBIAN_FRONTEND=noninteractive \
    apt-get install -y software-properties-common gpg-agent curl sudo tzdata \
    add-apt-repository ppa:deadsnakes/ppa -y \
    apt-get update \
    apt-get install -y python3.12 python3.12-venv \
    curl -LsSf https://astral.sh/uv/install.sh | sh \
    mv ~/.local/bin/uv /usr/local/bin/uv \
    uv venv --python python3.12 \
    uv pip install --no-cache ansible ansible-lint

WORKDIR /app

