---
- name: Play for Mac
  hosts: local
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: false
  become_user: "{{ user }}"
  roles:
    - { role: brew, tags: brew }
    - { role: mise, tags: [mise, mise_i] }
    - { role: actionlint, tags: actionlint }
    - { role: reviewdog, tags: reviewdog }
