---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - { role: zsh, tags: zsh }
    - { role: common, tags: common }
    - { role: peco, tags: peco }
    - { role: jq, tags: jq }
    # - { role: notofont, tags: notofont } # require exclude yum
    # - { role: by_pip,  tags: by_pip } # cheat, mycli, awscli

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  become_user: "{{ user }}"
  roles:
    - { role: preconfig, tags: preconfig }
    - { role: anyenv , tags: anyenv }
    - { role: powerline               , tags: powerline }
    - { role: zsh_syntax_highlighting , tags: zsh_syntax_highlighting }
    - { role: postconfig              , tags: postconfig }


