---
- name: Play for Ubuntu(root)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: true
  roles:
    - { role: packages, tags: [packages, common, init, tool, dev] }
    - { role: language-dependencies, tags: [anyenv, language] }
    - { role: common, tags: [common, init, tool, anyenv] }
    - { role: git, tags: [git, deploy, anyenv] }
    - { role: zsh, tags: [zsh, init, anyenv] }
    - { role: peco, tags: [peco, init] }
    # - { role: jq, tags: [jq, init] }
    - { role: tmux, tags: [tmux, init] }
    # - { role: bat, tags: [bat, tool] }
    # - { role: delta, tags: [delta] }
    - { role: vim8, tags: [vim8, vim] }
    # - { role: terraform, tags: [terraform, tool] }
    - { role: notofont, tags: [notofont, init] }
    - { role: by_pip, tags: [by_pip, init] }  # cheat, mycli
    # - { role: awscli, tags: [awscli, tool] }
    - { role: fillin, tags: [fillin, tool] }
    - { role: actionlint, tags: [actionlint, tool] }
    - { role: reviewdog, tags: [reviewdog, tool] }
    - { role: duckdb, tags: [duckdb, tool] }
    - { role: agg, tags: [agg, tool] }
    - { role: gh, tags: [gh, tool] }
    - { role: chrome, tags: [chrome, init]}

- name: Play for Ubuntu(User)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: false
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
    # - { role: anyenv, tags: anyenv }
    - { role: direnv, tags: [direnv, init] }
    - { role: powerline, tags: [powerline, init] }
    - { role: vim-plugins, tags: [vim-plugins, vim] }
    # - { role: gh-ext, tags: [gh-ext, gh, tool] } # execution after gh auth login
