---
- name: Play for Ubuntu(root)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: true
  roles:
    - { role: packages, tags: [packages, common, init, tool] }
    - { role: language-dependencies, tags: [common, init, language] }
    - { role: common, tags: [common, init, tool] }
    - { role: git, tags: [git, deploy] }
    - { role: zsh, tags: [zsh, init] }
    - { role: peco, tags: [peco, init] }
    - { role: tmux, tags: [tmux, init] }
    - { role: vim8, tags: [vim8, vim] }
    - { role: notofont, tags: [notofont, init] }
    - { role: by_pip, tags: [by_pip, init] }  # cheat, mycli
    - { role: fillin, tags: [fillin, tool] }
    - { role: actionlint, tags: [actionlint, tool] }
    - { role: reviewdog, tags: [reviewdog, tool] }
    - { role: duckdb, tags: [duckdb, tool] }
    - { role: agg, tags: [agg, tool] }
    - { role: gh, tags: [gh, tool] }
    - { role: chrome, tags: [chrome, init]}

- name: Play for Ubuntu(User)
  hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
    - versions_vars.yml
  become: false
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
    - { role: direnv, tags: [direnv, init] }
    - { role: powerline, tags: [powerline, init] }
    - { role: vim-plugins, tags: [vim-plugins, vim] }
    # - { role: gh-ext, tags: [gh-ext, gh, tool] } # execution after gh auth login
