---
- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: yes
  roles:
    - { role: common, tags: [common, init, tool] }
    - { role: git, tags: [git, deploy] }
    - { role: zsh, tags: [zsh, init] }
    - { role: peco, tags: [peco, init] }
    - { role: jq, tags: [jq, init] }
    - { role: bat, tags: [bat, tool] }
    - { role: notofont, tags: [notofont, init] }
    - { role: by_pip, tags: [by_pip, init] }  # cheat, mycli, awscli

- hosts: localhost
  # strategy: debug
  vars_files:
    - common_vars.yml
  become: no
  become_user: "{{ user }}"
  roles:
    - { role: deploy, tags: deploy }
    - { role: anyenv, tags: [anyenv, init] }
    # - { role: direnv, tags: [direnv, init]}
    - { role: powerline, tags: [powerline, init] }
    - { role: zsh_syntax_highlighting, tags: [zsh_syntax_highlighting, init] }
    - { role: vim-plugins, tags: [vim-plugins, init] }
