---
- name: Exist actionlint  # noqa command-instead-of-shell
  ansible.builtin.shell: command -v actionlint
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: actionlint_exist
  changed_when: false
  ignore_errors: true

- name: Get actionlint version
  ansible.builtin.shell: actionlint --version | head -n 1
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: actionlint_current_version
  changed_when: false
  ignore_errors: true
  when: actionlint_exist.rc == 0

- name: Check and install
  when: actionlint_exist.rc != 0 or ( actionlint_current_version is defined and actionlint_current_version.stdout.find(actionlint_version) == -1 )
  block:
    - name: Get tar.gz
      ansible.builtin.get_url:
        url: "{{ actionlint.src.darwin }}"
        dest: /tmp/{{ actionlint.tgz }}
      when: ansible_os_family == 'Darwin'

    - name: Get tar.gz
      ansible.builtin.get_url:
        url: "{{ actionlint.src.linux }}"
        dest: /tmp/{{ actionlint.tgz }}
      when: ansible_os_family != 'Darwin'

    - name: Unarchive zip
      ansible.builtin.unarchive:
        src: /tmp/{{ actionlint.tgz }}
        dest: /tmp/
        copy: false

    - name: Install
      changed_when: true
      ansible.builtin.command: mv /tmp/actionlint /usr/local/bin/actionlint
