---
- name: Exist jo
  ansible.builtin.command: which jo
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: exist_jo
  changed_when: false
  ignore_errors: true

- name: Get jo version
  ansible.builtin.command: jo -v
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  register: version_in_jo
  changed_when: false
  ignore_errors: true
  when: exist_jo.rc == 0

- block:
    - name: Get source
      ansible.builtin.get_url:
        url: "{{ jo.src }}"
        dest: /tmp/{{ jo.tgz }}

    - name: Unarchive tar.gz
      ansible.builtin.unarchive:
        src: /tmp/{{ jo.tgz }}
        dest: /tmp
        copy: false

    - name: Configure make install jo
      ansible.builtin.command: chdir=/tmp/{{ jo.dir }} {{ item }}
      changed_when: true
      with_items:
        - ./configure
        - make
        - make install

  when: exist_jo.rc != 0 or ( version_in_jo is defined and version_in_jo.stdout.find(jo_version) == -1 )
