---
- name: Install samba
  ansible.builtin.yum: name=samba state=installed
- name: Set config
  ansible.builtin.template: src=smb.conf dest=/etc/samba/smb.conf mode=0644
  register: samba_config
  notify: Restart samba

- name: Running samba
  ansible.builtin.service: name=smb state=started enabled=yes
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"
