---
- name: install samba
  yum: name=samba state=installed

- name: set config
  template: src=smb.conf dest=/etc/samba/smb.conf mode=0644
  register: samba_config
  notify: restart samba

- name: running samba
  service: name=smb state=started enabled=yes
  when: ansible_env.get('CI', None) and ansible_env.CI != "true"
