---
- name: Directory
  ansible.builtin.file:
    path: /usr/share/fonts/{{ item.key }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_dict: "{{ fonts }}"

- name: Get zip
  ansible.builtin.get_url:
    url: "{{ item.value.src }}"
    dest: /tmp/{{ item.value.zip }}
    mode: 0600
  with_dict: "{{ fonts }}"

- name: Unarchive zip
  ansible.builtin.unarchive:
    src: /tmp/{{ item.value.zip }}
    dest: /usr/share/fonts/{{ item.key }}/
    copy: false
  with_dict: "{{ fonts }}"

- name: Font-cache
  ansible.builtin.command:
    cmd: fc-cache -fv
  changed_when: true
