---
- name: Directory
  ansible.builtin.file:
    path: /usr/share/fonts/noto
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Get zip
  ansible.builtin.get_url:
    url: "{{ notofont.src }}"
    dest: /tmp/{{ notofont.zip }}
    mode: 0600

- name: Unarchive zip
  ansible.builtin.unarchive:
    src: /tmp/{{ notofont.zip }}
    dest: /usr/share/fonts/noto/
    copy: false

- name: Change permission file list
  ansible.builtin.find:
    paths: /usr/share/fonts/noto/
    patterns: "*.otf"
  register: notofont_otf_files

- name: Change permission
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0644"
  with_items:
    - "{{ notofont_otf_files.files }}"

- name: Font-cache
  ansible.builtin.command:
    cmd: fc-cache -fv
    creates: /usr/share/fonts/noto/*.otf
