---
- name: Set vim neobundle directory
  ansible.builtin.file:
    path: "{{ vim.neobundle.parent_dir }}"
    state: directory
    mode: "0755"

- name: Set vim neobundle
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  ansible.builtin.git:
    repo: "{{ vim.neobundle.src }}"
    dest: "{{ vim.neobundle.parent_dir }}/{{ vim.neobundle.dest_dir }}"
    clone: true

- name: Set vim neobundle  # noqa ignore-errors command-instead-of-shell
  ansible.builtin.shell: "{{ execute }} 'sh {{ dotfiles.dest }}/neobundle {{ dotfiles.dest }}/vimrc/rc/plugins.vim'"
  changed_when: true
  ignore_errors: true
