---
name: update versions

on:
  push:
    paths:
      - '.github/workflows/update-versions.yml'
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  versions-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - name: peco
            repo: peco/peco
            type: normal
          - name: bat
            repo: sharkdp/bat
            type: normal
          - name: docker_compose
            repo: docker/compose
            type: beta-rc
          - name: docker
            repo: docker/docker-ce
            type: beta-rc
          - name: embulk
            repo: embulk/embulk
            type: prefix
          - name: git
            repo: git/git
            type: from-tag
          - name: vim
            repo: vim/vim
            type: from-tag
          - name: jo
            repo: jpmens/jo
            type: prefix
          - name: jq
            repo: stedolan/jq
            type: prefix
          - name: q
            repo: harelba/q
            type: from-tag
          - name: terraform
            repo: hashicorp/terraform
            type: from-tag
          - name: zsh
            repo: zsh-users/zsh
            type: from-tag
          - name: tmux
            repo: tmux/tmux
            type: prefix
    steps:
      - uses: actions/checkout@master
      - name: install jq
        run: |
          sudo apt update
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          sudo python get-pip.py
          sudo apt install -y jq
      - name: install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt install -y yq
      - name: update versions.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/workflows/bin/update-version.sh ${{ matrix.role.name }} ${{ matrix.role.repo }} ${{ matrix.role.type }}
