---
- name: Install GitHub CLI Extension
  command: gh ext install {{ item }}
  with_items:
    - yusukebe/gh-markdown-preview
    - swfz/gh-ap
    - swfz/gh-annotations
    - github/gh-copilot
    - kawarimidoll/gh-graph
